### ISSUE TITLE
Web: League overhaul

### ISSUE THREAD

**Issue by hafager** [paradise-fantasy/fantasy#158]
- [ ] Should show weekly score and total score.
- [ ] Should  be able to sort by different columns
- [ ] Should look better
- [ ] Should show rank
- [ ] Should show places advanced or lost
- [ ] Should be able to leave league
- [ ] Should be an league-captain
- [ ] Total participants seems to be wrong
- [ ] Should have copy league code button in league (and in leagues view?)
- [ ] Shared ranking for same score

**Comment by tormiss** [comment]
League captain - could this be the owner of the league?
 In that case a matter of simply implementing this by showing it and allow a captain to hand over the league to another user

**Comment by hafager** [comment]
Example for wrong amount of total participants: Gobi (BJPBfHBig) and Ofisiell NHH-liga (B1ejLL4oe)

**Comment by kjetilbk** [comment]
Suggestion: Graph over historical points in a league
