### ISSUE TITLE
Change contestant is reliant on system clock

### ISSUE THREAD

**Issue by tormiss** [paradise-fantasy/fantasy#41]
Discovered that the lock that prevents changing/swapping contestants is reliant on the local system clock. Got a lock on one out of two computers where the unlocked one was about 7 minutes behind. Refresh of the page did not correct this until the local clock was past 21.00.

**Comment by Khrall** [comment]
Tror dette er akseptabelt. Er nok veldig få som opplever dette, og APIet skal uansett beskyttet. Kan fikse problemet, men tror det koster mer enn det er verdt 💸
