### ISSUE TITLE
Admin: Pagination of users. Should also add user search.

### ISSUE THREAD

**Issue by hafager** [paradise-fantasy/fantasy#70]

**Comment by tormiss** [comment]
Four issues:

1. CSS does not show up correctly. Pagination is left aligned and without styling (-style)
2. Backwards pagination does not exist/work properly. Once you select a number you cannot choose the previous without using the arrows. Should probably not "scroll" before middle number is the active one.
3. Possible to go backwards when at page 1. Results in empty pagination.
4. Possible to go forwards when at last page. Results in emtpy pagination.

Issues should be resolved before new merge is commited.
