### ISSUE TITLE
API: Log all errors to console

### ISSUE THREAD

**Issue by Khrall** [paradise-fantasy/fantasy#99]

**Comment by larseen** [comment]
Could look into using something like [sentry](https://sentry.io/pricing/), its free if you only have one user :).
Or you could self host it in AWS!

**Comment by tormiss** [comment]
In general, a log collection and visualization platform should be used to monitor all servers, instances and processes. Splunk works great, but is an expensive enterprise tool. ELK Stack/Elatic Stack is a great opensource alternative.

**Comment by larseen** [comment]
Of course, why not both? 😄 
Look into creating a middleware to catch all the errors at the very bottom of your router, and then just write `.catch(next)` to pass all errors to this middleware, then you only have one log and have centralized all error handling at one place 👍
